FROM python:3.9-slim

WORKDIR /app
RUN pip install poetry
COPY . .
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

EXPOSE 8000
EXPOSE 5678

CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]